//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kokpit.Dane {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogowanieRejestracjaRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogowanieRejestracjaRes() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kokpit.Dane.LogowanieRejestracjaRes", typeof(LogowanieRejestracjaRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu select top 1 uzytkownicy.id_uzytkownika, (imie+&apos; &apos;+nazwisko) as ImieNazwisko from loginy
        ///left join uzytkownicy on loginy.id_loginu=uzytkownicy.id_loginu
        ///left join dane_osobowe on uzytkownicy.id_danych_osobowych = dane_osobowe.id_danych_osobowych
        ///left join role on role.id_roli=dane_osobowe.id_roli
        ///where loginy.login=@login and UPPER(hash_hasla)=UPPER(@password) and kod_roli=@kod_roli.
        /// </summary>
        internal static string sqlCmdAutoryzacja {
            get {
                return ResourceManager.GetString("sqlCmdAutoryzacja", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu INSERT INTO dbo.operacja_zapomnialem_hasla (id_przypomnienia, id_uzytkownika, wygenerowany_kod, data_utworzenia, data_wykorzystania)
        ///VALUES ((SELECT ISNULL(MAX(id_przypomnienia) + 1, 1) FROM dbo.operacja_zapomnialem_hasla), @id_uzytkownika, @wygenerowany_kod, @data_utworzenia, NULL);.
        /// </summary>
        internal static string sqlCmdInsertDoTabeliOperacjaZapomnialemHasla {
            get {
                return ResourceManager.GetString("sqlCmdInsertDoTabeliOperacjaZapomnialemHasla", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SELECT TOP 1 wygenerowany_kod FROM dbo.operacja_zapomnialem_hasla WHERE wygenerowany_kod = @wygenerowany_kod;.
        /// </summary>
        internal static string sqlCmdSprawdzCzyWygenerowanyKodIstniejeWBazie {
            get {
                return ResourceManager.GetString("sqlCmdSprawdzCzyWygenerowanyKodIstniejeWBazie", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SELECT TOP 1 data_utworzenia, data_wykorzystania FROM dbo.operacja_zapomnialem_hasla WHERE wygenerowany_kod = @wygenerowany_kod.
        /// </summary>
        internal static string sqlCmdSzukajDatyUtworzeniaOrazDatyWykorzystaniaWygenerowanegoKodu {
            get {
                return ResourceManager.GetString("sqlCmdSzukajDatyUtworzeniaOrazDatyWykorzystaniaWygenerowanegoKodu", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SELECT hash_hasla FROM dbo.loginy WHERE id_loginu in (SELECT id_loginu from dbo.loginy WHERE id_loginu in (SELECT id_loginu FROM dbo.uzytkownicy WHERE id_uzytkownika in (SELECT id_uzytkownika FROM dbo.operacja_zapomnialem_hasla WHERE wygenerowany_kod = @wygenerowany_kod))).
        /// </summary>
        internal static string sqlCmdSzukajHaslaPoWygenerowanymKodzie {
            get {
                return ResourceManager.GetString("sqlCmdSzukajHaslaPoWygenerowanymKodzie", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select id_uzytkownika from dbo.uzytkownicy where id_loginu in (Select id_loginu from dbo.loginy where login=@login).
        /// </summary>
        internal static string sqlCmdSzukajIdUzytkownikaPoLoginie {
            get {
                return ResourceManager.GetString("sqlCmdSzukajIdUzytkownikaPoLoginie", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu UPDATE dbo.operacja_zapomnialem_hasla SET data_wykorzystania = @data_wykorzystania WHERE wygenerowany_kod = @wygenerowany_kod.
        /// </summary>
        internal static string sqlCmdUstawDateWykorzystaniaWygenerowanegoKodu {
            get {
                return ResourceManager.GetString("sqlCmdUstawDateWykorzystaniaWygenerowanegoKodu", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu UPDATE dbo.loginy SET hash_hasla = @hash_hasla WHERE id_loginu in (SELECT id_loginu from dbo.loginy WHERE id_loginu in (SELECT id_loginu FROM dbo.uzytkownicy WHERE id_uzytkownika in (SELECT id_uzytkownika FROM dbo.operacja_zapomnialem_hasla WHERE wygenerowany_kod = @wygenerowany_kod))).
        /// </summary>
        internal static string sqlCmdZmienHaslo {
            get {
                return ResourceManager.GetString("sqlCmdZmienHaslo", resourceCulture);
            }
        }
    }
}
