//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kokpit.Dane {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogowanieRejestracjaRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogowanieRejestracjaRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kokpit.Dane.LogowanieRejestracjaRes", typeof(LogowanieRejestracjaRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top 1 uzytkownicy.id_uzytkownika from loginy
        ///left join uzytkownicy on loginy.id_loginu=uzytkownicy.id_loginu
        ///left join dane_osobowe on uzytkownicy.id_danych_osobowych = dane_osobowe.id_danych_osobowych
        ///left join role on role.id_roli=dane_osobowe.id_roli
        ///where loginy.login=@login and hash_hasla=@password and kod_roli=@kod_roli.
        /// </summary>
        internal static string sqlCmdAutoryzacja {
            get {
                return ResourceManager.GetString("sqlCmdAutoryzacja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO dbo.operacja_zapomnialem_hasla (id_przypomnienia, id_uzytkownika, wygenerowany_kod, data_utworzenia, data_wykorzystania)
        ///VALUES ((SELECT ISNULL(MAX(id_przypomnienia) + 1, 1) FROM dbo.operacja_zapomnialem_hasla), @id_uzytkownika, @wygenerowany_kod, @data_utworzenia, NULL);.
        /// </summary>
        internal static string sqlCmdInsertDoTabeliOperacjaZapomnialemHasla {
            get {
                return ResourceManager.GetString("sqlCmdInsertDoTabeliOperacjaZapomnialemHasla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 wygenerowany_kod FROM dbo.operacja_zapomnialem_hasla WHERE wygenerowany_kod = @wygenerowany_kod;.
        /// </summary>
        internal static string sqlCmdSprawdzCzyWygenerowanyKodIstniejeWBazie {
            get {
                return ResourceManager.GetString("sqlCmdSprawdzCzyWygenerowanyKodIstniejeWBazie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 data_utworzenia, data_wykorzystania FROM dbo.operacja_zapomnialem_hasla WHERE wygenerowany_kod = @wygenerowany_kod.
        /// </summary>
        internal static string sqlCmdSzukajDatyUtworzeniaOrazDatyWykorzystaniaWygenerowanegoKodu {
            get {
                return ResourceManager.GetString("sqlCmdSzukajDatyUtworzeniaOrazDatyWykorzystaniaWygenerowanegoKodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select id_uzytkownika from dbo.uzytkownicy where id_loginu in (Select id_loginu from dbo.loginy where login=@login).
        /// </summary>
        internal static string sqlCmdSzukajIdUzytkownikaPoLoginie {
            get {
                return ResourceManager.GetString("sqlCmdSzukajIdUzytkownikaPoLoginie", resourceCulture);
            }
        }
    }
}
