//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formularze.Dane {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DokumentyRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DokumentyRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Formularze.Dane.DokumentyRes", typeof(DokumentyRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO dbo.dokumenty (nazwa_dokumentu, data_modyfikacji_pliku, data_wrzucenia_pliku, plik, id_przesylajacego) VALUES (@nazwa_dokumentu, @data_modyfikacji_pliku, @data_wrzucenia_pliku, @plik, @id_przesylajacego).
        /// </summary>
        internal static string SqlCmdDodajDokument {
            get {
                return ResourceManager.GetString("SqlCmdDodajDokument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM dbo.dokumenty WHERE id_dokumentu = @id_dokumentu.
        /// </summary>
        internal static string SqlCmdPobierzDokument {
            get {
                return ResourceManager.GetString("SqlCmdPobierzDokument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top (@ilosc) *
        ///from dbo.dokumenty
        ///order by data_wrzucenia_pliku DESC.
        /// </summary>
        internal static string SqlCmdPobierzTopIloscDokumentow {
            get {
                return ResourceManager.GetString("SqlCmdPobierzTopIloscDokumentow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT imie, nazwisko FROM dbo.dane_osobowe WHERE id_danych_osobowych in (SELECT id_uzytkownika =  @id_przesylajacego).
        /// </summary>
        internal static string SqlCmdZnajdzPrzesylajacegoPoId_przesylajacego {
            get {
                return ResourceManager.GetString("SqlCmdZnajdzPrzesylajacegoPoId_przesylajacego", resourceCulture);
            }
        }
    }
}
